version: "2"
services:
  dynamodb:
    image: amazon/dynamodb-local:2.5.3
    restart: always
    entrypoint: java
    command: "-jar DynamoDBLocal.jar -sharedDb"
    ports:
      - "8808:8000"

  init-dynamo:
    image: garland/aws-cli-docker
    command: >
      sh -c "aws dynamodb create-table --table-name LocksTestTable --attribute-definitions AttributeName=LockKey,AttributeType=S --key-schema AttributeName=LockKey,KeyType=HASH --provisioned-throughput ReadCapacityUnits=1,WriteCapacityUnits=1 --endpoint-url http://dynamodb:8000 &&
             sleep 5"
    environment:
      - AWS_ACCESS_KEY_ID=0
      - AWS_SECRET_ACCESS_KEY=0
      - AWS_DEFAULT_REGION=eu-central-1
    depends_on:
      - dynamodb

  integration_tests:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - .:/code
    working_dir: /code
    command: bash -c "dotnet tool restore && dotnet paket restore && dotnet run --project tests --sequenced --no-spinner"
    environment:
      - DYNAMO_LOCAL_URL=http://dynamodb:8000
    depends_on:
      - init-dynamo
